development:
  username: postgres
  adapter: postgresql
  password: postgres
  database: genevarb_pres_development
  host: localhost

test:
  username: postgres
  password: postgres
  adapter: postgresql
  database: genevarb_pres_test
  host: localhost
